#!/bin/sh
# ci_pre_xcodebuild.sh
# Xcode Cloud のビルド前に Secrets.swift を環境変数から自動生成するスクリプト
# 環境変数 ANTHROPIC_API_KEY と TAVILY_API_KEY を Xcode Cloud に登録してください

set -e

# CI_PRIMARY_REPOSITORY_PATH = リポジトリのルートディレクトリ
SECRETS_DIR="$CI_PRIMARY_REPOSITORY_PATH/BuyOrNot/Config"
SECRETS_FILE="$SECRETS_DIR/Secrets.swift"

echo "Generating Secrets.swift at $SECRETS_FILE ..."

mkdir -p "$SECRETS_DIR"

cat > "$SECRETS_FILE" << EOF
// Secrets.swift - Auto-generated by ci_pre_xcodebuild.sh
// Do not edit manually.

enum Secrets {
    static let anthropicAPIKey = "${ANTHROPIC_API_KEY}"
    static let tavilyAPIKey    = "${TAVILY_API_KEY}"
}
EOF

echo "Secrets.swift generated successfully."
